/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "eorejdmwrjegmblltxtj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvcmVqZG13cmplZ21ibGx0eHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzMTk2ODYsImV4cCI6MjA3ODg5NTY4Nn0.laLWdu-sgqh2e6QmI-V2PhpZxsoYJ9c01kh9bjq0EK8"